// Auto-generated from Mixpanel project 3191947
// These are all active (non-hidden, non-dropped) events
// Update periodically by running: GET /api/mixpanel-meta?kind=events

export const SOULSENSEI_EVENTS = [
  // Custom events (display name first where available)
  'Overall PV',
  'Overall Page Views',
  'Overall Course PV',
  'Overall Course Page Views',
  'Overall Join Page Views',
  'Overall 1:1 Page Views',
  'Overall Course Listing Page',
  'Overall Module Page Visitors',
  'Overall Hamburger',
  'Paid Sessions Page Views',
  'RC Combined',
  'Card Click Bottom Nav',
  'APP Home Engagement',
  'Login Signup',
  'Razorpay Payment Attempt',
  '1:1 Overall Listing Page View',
  // Core funnel events
  'page_view',
  'register_click',
  'register_succeed',
  'first_register_succeed',
  'login_succeed',
  'login_failed',
  'signup_succeed',
  'signup_failed',
  'send_otp_click',
  'submit_otp_click',
  // Payment events
  'proceed_checkout',
  'checkout_click',
  'cart_succeed',
  'cart_success',
  'cart_added_combined',
  'payment_cta_click',
  'pay_cta_click',
  'razorpay_order_paid',
  'razorpay_payment_authorized',
  'razorpay_payment_captured',
  'razorpay_payment_failed',
  'apply_coupon',
  'remove_coupon',
  // Session events
  'app_open',
  'app_installed',
  'join_live_session_clicked',
  'join_session_clicked',
  'meeting_joined',
  'meeting_ended',
  'meeting_left',
  'live_session_started',
  'live_session_ended',
  'slot_selected',
  'confirm_slot_click',
  'choose_slot_click',
  'reserve_now_clicked',
  'reserve_spot_clicked',
  'join_page_view',
  'reg_click_confirm_slot',
  // Engagement events
  'card_click',
  'bottom_nav_clicked',
  'tab_click',
  'item_click',
  'subscribe_click',
  'push_notification_clicked',
  'push_notification_viewed',
  'trigger_banner_click',
  'trigger_banner_view',
  'hamburger_click',
  'hamburger_clicked',
  'hamburger_l1_click',
  'hamburger_l2_click',
  'hamburger_leader_click',
  'hamburger_membership_click',
  'hamburger_live_card_click',
  // Playback events
  'play_start',
  'play_exit',
  'play_duration_25',
  'play_duration_50',
  'play_duration_75',
  'play_duration_90',
  'play_duration_100',
  'pause_click',
  'resume_click',
  // System/Auto events
  '$mp_web_page_view',
  '$ae_first_open',
  '$ae_session',
  '$session_start',
  '$session_end',
].sort();

// Top properties per key event — for filter suggestions in Explore
export const EVENT_TOP_PROPERTIES = {
  'register_succeed': ['utm_source', 'utm_medium', 'utm_campaign', 'platform', 'city', 'country'],
  'page_view': ['page_name', 'platform', 'utm_source', 'utm_medium'],
  'login_succeed': ['platform', 'method'],
  'razorpay_payment_captured': ['amount', 'currency', 'plan_name', 'platform'],
  'app_open': ['platform', 'app_version', 'country'],
  '$mp_web_page_view': ['$current_url', '$referrer', 'utm_source', 'utm_medium'],
  'Overall PV': ['platform', 'country'],
};
